[package]
name = "test01"
version = "0.1.0"
authors = ["Szymon Sapkowski <szymon.sapkowski@samba.tv>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
